tibber:
  pulse:
    source: ${TIBBER_PULSE_SOURCE}
    http:
      host: ${TIBBER_PULSE_HOST}
      nodeId: ${TIBBER_PULSE_NODE_ID:1}
      url: ${TIBBER_PULSE_URL:http://${tibber.pulse.http.host}/data.json?node_id=${tibber.pulse.http.nodeId}}
      username: ${TIBBER_PULSE_USERNAME:}
      password: ${TIBBER_PULSE_PASSWORD:}
      cron: ${TIBBER_PULSE_CRON:*/15 * * * * *}
    mqtt:
      host: "${MQTT_SOURCE_HOST}"
      port: "${MQTT_SOURCE_PORT:1883}"
      username: "${MQTT_SOURCE_USERNAME:}"
      password: "${MQTT_SOURCE_PASSWORD:}"
      topic: "${MQTT_SOURCE_TOPIC}"

sml:
  ignoreCrcErrors: ${IGNORE_SML_CRC_ERRORS:false}

logging:
  level:
    ROOT: warn
    de.wyraz.tibberpulse: ${LOG_LEVEL:info}
    
publish:
  filters: ${PUBLISH_FILTERS:}
  interval: "${PUBLISH_INTERVAL:}"
  mqtt:
    enabled: "${PUBLISH_MQTT_ENABLED:false}"
    host: "${PUBLISH_MQTT_HOST}"
    port: "${PUBLISH_MQTT_PORT:1883}"
    username: "${PUBLISH_MQTT_USERNAME:}"
    password: "${PUBLISH_MQTT_PASSWORD:}"
    topic: "${PUBLISH_MQTT_TOPIC:{meterId}/{nameOrObisCode}}"
    payload: "${PUBLISH_MQTT_VALUE:{value}}"
  openmetrics:
    enabled: "${PUBLISH_OPENMETRICS_ENABLED:false}"
    url: "${PUBLISH_OPENMETRICS_URL}"
    username: "${PUBLISH_OPENMETRICS_USERNAME:}"
    password: "${PUBLISH_OPENMETRICS_PASSWORD:}"
    